---
apiVersion: app/v1
kind: deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
    replica: 2
    selector:
        matchLabel:
            app: nginx
    template:
        metadata:
          labels:
            app: nginx
        spec:
          container:
          - name: nginx
            image: nginx:1.16
            port:
              -containerPort: 80

## EOF ###


        